version: '3'

services:
  backend:
    build: ./backend
    image: giftig/go:2
    ports:
      - 8081:8080
    volumes:
      - ${GO_REDIRECT_DIR}:/usr/src/db

  frontend:
    build: ./frontend
    image: giftig/go-static:2
    ports:
      - 8080:80
    depends_on:
      - backend
